services:
  app:
    container_name: innoscripta_app
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USERNAME}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: always
    volumes:
      - news_aggregator_api-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - docker-network

volumes:
  news_aggregator_api-db-data:

networks:
  docker-network:
    driver: bridge
